config/routes.rb
Rss::Application.routes.draw do
  resources :feed_entries

  resources :tags

  resources :sources

  root :to => 'feed_entries#view_all'

  match 'entries' => 'feed_entries#index'
  match 'entries/by_tag' => 'tags#view_all'

  match 'sources' => 'SourcesController#index'
  match 'cron' => 'Cron#index'
  match 'retag' => 'Cron#retag'

end

app/models/feed_entry.rb
class FeedEntry < ActiveRecord::Base
  has_and_belongs_to_many :tags

  def self.from_entry(entry)
    if exists? :guid => entry.id
      array = self.all :conditions => ["guid = ?", entry.id]
      return array.first
    end
    e = self.new :title         => entry.title,
                 :summary      => entry.summary,
                 :url          => entry.url,
                 :published_at => entry.published,
                 :guid         => entry.id
  end

  def check_for_tags(tags)
    self.has_tag = false
    tags.each do |tag|
      has_tag = false
      if title.downcase.include? tag.name.downcase
        has_tag = true
      end

      if summary.downcase.include? tag.name.downcase
        has_tag = true
      end

      if has_tag
        self.add_tag tag
        self.has_tag = true
        save
      end
    end
  end

  def add_tag(tag)
    unless self.tags.include?(tag)
      self.tags << tag
    end
  end

  def get_tag_string
    if self.tags.count == 0
      return "None"
    end

    self.get_tag_names.join(', ')
  end

  def get_tag_names
    
    names = Array.new
    self.tags.each do |t|
      names << t.name
    end

    names
  end

  def self.get_feed(feed_url)
    Feedzirra::Feed.fetch_and_parse(feed_url)
  end

  def self.update_from_feed(feed_url)
    feed = self.get_feed( feed_url )
    add_entries(feed.entries)
  end
  
  private
  
  def self.add_entries(entries)
    entries.each do |entry|
      unless exists? :guid => entry.id
        create!(
          :title         => entry.title,
          :summary      => entry.summary,
          :url          => entry.url,
          :published_at => entry.published,
          :guid         => entry.id
        )
      end
    end
  end
end

app/controllers/feed_entries_controller.rb
class FeedEntriesController < ApplicationController
  # GET /feed_entries
  # GET /feed_entries.json
  def index
    @feed_entries = FeedEntry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feed_entries }
    end
  end

  def view_all
    @tags = Tag.all

    if params[:tag]
      @tag = Tag.find params[:tag]
      @entries = @tag.feed_entries
    else
      @entries = FeedEntry.all :order => "published_at DESC"
    end
  end

  def view_tagged
    @entries = FeedEntry.find :all, :conditions => ["has_tag=?", true], :order => "published_at DESC"
  end

  # GET /feed_entries/1
  # GET /feed_entries/1.json
  def show
    @feed_entry = FeedEntry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feed_entry }
    end
  end

  # GET /feed_entries/new
  # GET /feed_entries/new.json
  def new
    @feed_entry = FeedEntry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feed_entry }
    end
  end

  # GET /feed_entries/1/edit
  def edit
    @feed_entry = FeedEntry.find(params[:id])
  end

  # POST /feed_entries
  # POST /feed_entries.json
  def create
    @feed_entry = FeedEntry.new(params[:feed_entry])

    respond_to do |format|
      if @feed_entry.save
        format.html { redirect_to @feed_entry, notice: 'Feed entry was successfully created.' }
        format.json { render json: @feed_entry, status: :created, location: @feed_entry }
      else
        format.html { render action: "new" }
        format.json { render json: @feed_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /feed_entries/1
  # PUT /feed_entries/1.json
  def update
    @feed_entry = FeedEntry.find(params[:id])

    respond_to do |format|
      if @feed_entry.update_attributes(params[:feed_entry])
        format.html { redirect_to @feed_entry, notice: 'Feed entry was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @feed_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feed_entries/1
  # DELETE /feed_entries/1.json
  def destroy
    @feed_entry = FeedEntry.find(params[:id])
    @feed_entry.destroy

    respond_to do |format|
      format.html { redirect_to feed_entries_url }
      format.json { head :ok }
    end
  end
end

app/helpers/feed_entries_helper.rb
module FeedEntriesHelper
end

app/views/feed_entries/_form.html.erb
<%= form_for(@feed_entry) do |f| %>
  <% if @feed_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed_entry.errors.count, "error") %> prohibited this feed_entry from being saved:</h2>

      <ul>
      <% @feed_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :summary %><br />
    <%= f.text_area :summary %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :published_at %><br />
    <%= f.datetime_select :published_at %>
  </div>
  <div class="field">
    <%= f.label :guid %><br />
    <%= f.text_field :guid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feed_entries/edit.html.erb
<h1>Editing feed_entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed_entry %> |
<%= link_to 'Back', feed_entries_path %>

app/views/feed_entries/index.html.erb
<h1>Listing feed_entries</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Summary</th>
    <th>Url</th>
    <th>Published at</th>
    <th>Guid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @feed_entries.each do |feed_entry| %>
  <tr>
    <td><%= feed_entry.title %></td>
    <td><%= truncate feed_entry.summary, :length => 10 %></td>
    <td><%= feed_entry.url %></td>
    <td><%= feed_entry.published_at %></td>
    <td><%= truncate feed_entry.guid, :length => 10 %></td>
    <td><%= link_to 'Show', feed_entry %></td>
    <td><%= link_to 'Edit', edit_feed_entry_path(feed_entry) %></td>
    <td><%= link_to 'Destroy', feed_entry, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Feed entry', new_feed_entry_path %>

app/views/feed_entries/new.html.erb
<h1>New feed_entry</h1>

<%= render 'form' %>

<%= link_to 'Back', feed_entries_path %>

app/views/feed_entries/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @feed_entry.title %> <%= link_to "[>]", @feed_entry.url %></h1>
<p>
  <%= @feed_entry.published_at %> 
  (<%= time_ago_in_words @feed_entry.published_at %> ago) | 
  <%= raw linked_tag_string @feed_entry.tags %>
</p>

<p class="summary"><%= raw @feed_entry.summary %></p>

<%= link_to 'Edit', edit_feed_entry_path(@feed_entry) %> |
<%= link_to 'Back', feed_entries_path %>

app/views/feed_entries/view_all.html.erb
<p id="notice"><%= notice %></p>

<h1>News</h1>

<% if @tag %>
<h2>For tag <%= @tag.name %></h2>
<% end %>


<p><% @tags.each do |t| %><%= link_to t.name, "/?tag=#{t.id}" %>, <%end%></p>

<% @entries.each do |e| %>
<div class="entry">
  <p><%= e.published_at %> <%= link_to "[>]", e.url %> <%= link_to truncate(e.title, :length => 70), e %> (<%= raw linked_tag_string e.tags %>)</p>
</div>
<%end%>

app/views/feed_entries/view_tagged.html.erb
<% @entries.each do |e| %>

<div class="tagged_entry">
  <p><%= link_to e.title, e, :class => "title" %></p>
  <p class="summary">from <%= link_to URI.parse( e.url ).host, e.url %> tagged with <%= raw linked_tag_string e.tags %> about <%= time_ago_in_words(e.published_at) %> ago</p>
</div>

<% end %>