config/routes.rb
Rss::Application.routes.draw do
  resources :feed_entries

  resources :tags

  resources :sources

  root :to => 'feed_entries#view_all'

  match 'entries' => 'feed_entries#index'
  match 'entries/by_tag' => 'tags#view_all'

  match 'sources' => 'SourcesController#index'
  match 'cron' => 'Cron#index'
  match 'retag' => 'Cron#retag'

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  before_create :create_slug
  has_and_belongs_to_many :feed_entries

  private

  def create_slug
    self.slug = self.name.parameterize
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.order "name ASC"

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag }
    end
  end

  def find_by_slug
    @tag = Tag.find_by_slug!(params[:slug])
    render :show
  end

  # GET /tags/new
  # GET /tags/new.json
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render json: @tag, status: :created, location: @tag }
      else
        format.html { render action: "new" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.json
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tags_helper.rb
module TagsHelper

  def linked_tag_string(tags)

    if tags.count < 1
    	return 'none'
    end

    links = Array.new
    tags.each do |t|
      links << link_to( t.name, "/tag/#{t.slug}" )
    end

    links.join(", ")
  end
end

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :slug %><br />
    <%= f.text_field :slug %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Tags</h1>

<p class="tag_cloud">
<% @tags.each do |t| %>

<%= link_to "#{t.name} (#{t.feed_entries.count})", "/tag/#{t.slug}" %> 

<% end %>
</p>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Tag: <%= @tag.name %></h1>

<% @tag.feed_entries.each do |e| %>

<div class="tagged_entry">
  <p><%= link_to e.title, e, :class => "title" %></p>
  <p class="summary">from <%= link_to URI.parse( e.url ).host, e.url %> tagged with <%= raw linked_tag_string e.tags %> about <%= time_ago_in_words(e.published_at) %> ago</p>
</div>

<% end %>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>

app/views/tags/view_all.html.erb
<h1>Viewing all tags and their entries</h1>

<% @tags.each do |t| %>

<div class="tag-entries">
	<h2><%= t.name %></h2>
	<% t.feed_entries.each do |e| %>
		<p>
			<%= e.published_at %> <%= link_to "[>]", e.url %> 
			<%= link_to truncate(e.title, :length => 100), e %> (<%= raw linked_tag_string e.tags %>)
		</p>
	<% end %>
	<h2 style="text-align: right;"><%= t.name %></h2>
</div>

<% end %>